start cmd /c "call log courier-service"
start cmd /c "call log admin-service"  
start cmd /c "call log user-service"   
start cmd /c "call log client-service"
start cmd /c "call log public-api"     
start cmd /c "call log database"       
start cmd /c "call log eureka-server"  
start cmd /c "call log rabbitmq"       