server:
  port: 8002
  
spring:
  datasource:
    url : "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host:  localhost
    port:  5672
    username: guest
    password: guest
logging:
    pattern:
       console: "%-5p %c{1}:%L %m requestId=%X{parcel_service_request_id} correlationId=%X{parcel_service_correlation_id}%n"
    level:
       com:
         stas:
           parceldelivery: DEBUG
       org:
           springframework:
              cloud:
                 openfeign: DEBUG
    
